# Generated by Django 5.1.4 on 2025-01-04 14:20

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Seen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Active User',
                'verbose_name_plural': 'Active Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('about', models.TextField(blank=True, max_length=200, null=True, verbose_name='About')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.TextField(max_length=300, verbose_name='Pages')),
                ('reports', models.TextField(max_length=300, verbose_name='Reports')),
                ('tables', models.TextField(max_length=1200, verbose_name='Tables')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_view', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User View',
                'verbose_name_plural': 'User Views',
            },
        ),
    ]
