# Generated by Django 5.1.4 on 2025-01-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_customer_is_active_historicalcustomer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendor',
            name='instapay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='instapay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
