# Generated by Django 5.1.4 on 2024-12-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_historicalvendor_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='operation.vendor'),
            preserve_default=False,
        ),
    ]
