# Generated by Django 5.1.4 on 2025-01-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_historicalvendor_instapay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquotation',
            name='internal_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='internal_id',
        ),
    ]
