# Generated by Django 5.1.4 on 2024-12-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_quotationline_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquotation',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='conditions',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='conditions',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
