# Generated by Django 5.1.4 on 2025-01-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_remove_historicalquotation_internal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='status',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Canceled', 'Canceled'), ('Invoice', 'Invoice'), ('Closed', 'Closed')], default='Quotation', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Canceled', 'Canceled'), ('Invoice', 'Invoice'), ('Closed', 'Closed')], default='Quotation', max_length=15, verbose_name='Status'),
        ),
    ]
