# Generated by Django 5.1.4 on 2025-01-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_historicalquotation_status_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='total_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
