# Generated by Django 5.1.4 on 2025-01-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_quotationline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operation.quotation'),
        ),
    ]
