# Generated by Django 5.1.4 on 2025-01-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_historicalquotation_profit_quotation_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquotation',
            name='purchase_order_description',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='purchase_order_description',
        ),
    ]
