# Generated by Django 5.1.4 on 2025-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_remove_historicalquotation_purchase_order_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationline',
            old_name='actual_quantity',
            new_name='quotation_quantity',
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='quotation_net_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='quotation_total_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_net_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_total_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='quotation_total_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
