# Generated by Django 5.1.4 on 2025-01-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_rename_profit_historicalquotation_profit_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='stock',
        ),
    ]
