# Generated by Django 5.1.4 on 2025-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_alter_historicalquotation_profit_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='total_cost',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_cost',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
