# Generated by Django 5.1.4 on 2025-01-24 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0009_alter_bankaccount_options_alter_country_options'),
        ('operation', '0023_quotationline_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='definitions.country'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='margin',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='sales_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
