# Generated by Django 5.1.4 on 2025-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_remove_historicalquotation_supply_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationattachment',
            name='file_name',
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='file_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
