# Generated by Django 5.1.4 on 2025-02-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0027_remove_quotationattachment_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
