# Generated by Django 5.1.4 on 2025-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0028_quotationattachment_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
