# Generated by Django 5.1.4 on 2025-02-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_historicalquotation_name_quotation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Insurance',
                'verbose_name_plural': 'Quotation Insurances',
            },
        ),
    ]
