# Generated by Django 5.1.4 on 2025-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_quotationinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='eta_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='eta_status_detailed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='eta_total_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eta_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eta_status_detailed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eta_total_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
