# Generated by Django 5.1.4 on 2025-03-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0031_historicalquotation_eta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquotation',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
