# Generated by Django 5.1.4 on 2025-03-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0032_alter_historicalquotation_uuid_alter_quotation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquotation',
            name='eta_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='eta_status_detailed',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='uuid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eta_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='eta_status_detailed',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='uuid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
