# Generated by Django 5.1.4 on 2025-06-30 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0033_alter_historicalquotation_eta_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
