# Generated by Django 5.1.4 on 2025-06-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0034_historicalquotation_date_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquotation',
            name='date_time_issued',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='date_time_issued',
        ),
    ]
