# Generated by Django 5.1.4 on 2025-01-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_alter_description_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittype',
            options={'ordering': ('code',)},
        ),
    ]
