# Generated by Django 5.1.4 on 2025-01-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0003_alter_unittype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('conditions', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
