# Generated by Django 5.1.4 on 2025-01-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0004_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='name',
        ),
    ]
