# Generated by Django 5.1.4 on 2025-01-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0005_rename_description_description_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Revenue', 'Revenue'), ('Expense', 'Expense')], default='Revenue', max_length=10)),
                ('type', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=6)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
