# Generated by Django 5.1.4 on 2025-01-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0008_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('account_name',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name_plural': 'Countries'},
        ),
    ]
